# Site settings
title:       melgenek
email:
author:      Yev Melnyk
description: "melgenek's blog"
baseurl:     ""
url:         "https://melgenek.github.io"
date_format: "%-d %b, %Y"

# Google services
google_verification: "27hdqSsss2dY8Qwz0b8nG4OiLhoU14L0YGEPqIbAQ5k"
# Use either direct GA implementation or set up GTM account
# - using both will skew your data (leave blank to not use at all)
google_analytics:

# Optional features
animated:             false
show_related_posts:   false
show_social_icons:    true
extended_fonts: true
enable_anchorjs: true

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname: melgenek-github-io

# Social icons
github_username: melgenek
twitter_username:
linkedin_username: yevhenii-melnyk

text:
  pagination:
    newer: 'Newer'
    older: 'Older'
  post:
    updated:        'Updated'
    minute_read:    'minute read'
    related_posts:  'Related Posts'
  index:
    coming_soon: 'Coming soon...'
  og_locale: 'en_US'

# Build settings
markdown:     kramdown
kramdown:
  parse_block_html: true

permalink:    :title
paginate:     4
paginate_path: /page/:num

sass:
  style: compressed
plugins:
  - jekyll-paginate
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - README.md
  - screenshot.png
  - vendor
  - .idea
